version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: final-back
    restart: always
    environment:
      MYSQL_DATABASE: 'dh202302-g2'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/your_sql_file.sql


volumes:
  mysql: